# Use Node.js image as base
FROM node:16.16.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy frontend source code
COPY . .

# Expose port
EXPOSE 3000

# Build the frontend
RUN npm run build

# Start the frontend server
CMD ["npm", "start"]
