# Use Node.js image as base
FROM node:20.10.0

# Set working directory
WORKDIR /server

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy backend source code
COPY . .

# Expose port
EXPOSE 5000

# Start the backend server
CMD [ "node" , "server.js" ]

